import click
from hyperion_node.services.server import HyperionServerService
from urllib.parse import urlparse

DEFAULT_PORT = HyperionServerService.DEFAULT_PORT


@click.group()
def server():
    pass


@server.command("add")
def add_hyperion_server():
    f"""
    Adds hyperion-node to a running hyperion instance
    """

    node_name = click.prompt("Please specify a name for this Hyperion runner:")

    host = click.prompt(
        "Please enter the hostname or IP of your Hyperion server:",
        default="http://localhost",
    )
    parsed_url = urlparse(host)
    scheme = parsed_url.scheme
    host = parsed_url.hostname
    port = parsed_url.port
    if not port:
        port = click.prompt(
            "Please enter the port of the server",
            default=2468,
            type=click.IntRange(1, 65535),
        )

    otp = click.prompt(
        "Please enter a valid OTP code generated by your hyperion instance:"
    )
    otp = otp.replace("-", "").replace("")

    service = HyperionServerService()

    try:
        # Ab hier läuft alles genau wie vorher!
        clean_host, clean_port = service.resolve_connection_details(
            address=str(parsed_url)
        )

        print(f"Verbinde zu: {clean_host}:{clean_port} ...")
        service.connect_server(host, port)

        click.secho(
            f"✅ Server {clean_host}:{clean_port} erfolgreich gespeichert!", fg="green"
        )

    except ValueError as e:
        raise click.BadParameter(str(e))
    except Exception as e:
        raise click.UsageError(f"Verbindung fehlgeschlagen: {e}")
