import click
from hyperion_node.services.server import HyperionServerService
from urllib.parse import urlparse
import re

DEFAULT_PORT = HyperionServerService.DEFAULT_PORT
OTP_VALIDATION = re.compile(r"^[A-Z0-9]{6}$")


@click.group()
def server():
    pass


@server.command("add")
def add_hyperion_server():
    f"""
    Adds hyperion-node to a running hyperion instance
    """

    node_name = click.prompt("Please specify a name for this Hyperion runner")

    host = click.prompt(
        "Please enter the hostname or IP of your Hyperion server",
        default="http://localhost",
    )
    parsed_url = urlparse(host)
    scheme = parsed_url.scheme
    host = parsed_url.hostname
    port = parsed_url.port
    if not port:
        port = click.prompt(
            "Please enter the port of the server",
            default=2468,
            type=click.IntRange(1, 65535),
        )

    otp = click.prompt(
        "Please enter a valid OTP code generated by your hyperion instance"
    )
    otp = otp.strip().upper()
    if not OTP_VALIDATION.match(otp):
        raise click.UsageError("OTP code does not match pattern. Try again")

    service = HyperionServerService()

    try:
        service.connect_server(f"{scheme}://{host}:{port}", otp, node_name)
    except ValueError as e:
        raise click.BadParameter(str(e))
    except Exception as e:
        raise click.UsageError(f"Verbindung fehlgeschlagen: {e}")
    
@server.command("list")
@click.option("--quiet", "-q", is_flag=True, help="Returns only server names without index.")
def list_all_servers(quiet):
    service = HyperionServerService()
    servers = service.get_all_servers()
    if quiet:
        # Nur die Server-Namen ausgeben
        for s in servers:
            click.echo(s)
    else:
        # Mit Index (hochzählend ab 1) ausgeben
        click.secho("List of servers:", bold=True, fg='cyan')
        for idx, s in enumerate(servers, start=1):
            click.echo(f"{idx}. {s}")


